service: ec2noip

package:
  exclude:
    - .serverless/**
    - .git/**
    - .gitignore
    - venv
    - node_modules/**

provider:
  name: aws
  runtime: python3.7
  memorySize: 128
  logRetentionInDays: 3

  region: eu-central-1

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:DescribeInstances"
        - "ec2:DescribeTags"
      Resource: "*"


functions:
  start:
    reservedConcurrency: 2
    handler: handler.start
    events:
      - cloudwatchEvent:
          event:
            source:
              - aws.ec2
            detail-type:
              - EC2 Instance State-change Notification
            detail:
              state:
                - running

plugins:
  - serverless-python-requirements
